Client side
sdswoc/rassasy pull request #2
Opened 2020-02-27 17:22 UTC by shreyaa-s

2020-03-14 04:37 UTC, karan0299 commented
As a good practice , always provide some description about the PR

2020-03-14 04:40 UTC, karan0299 commented on IRequest.php
> +}
insert new line at the end

2020-03-16 11:41 UTC, karan0299 commented on html/pastorder.php
> +        }); */
remove unnecessary comments

2020-03-16 13:49 UTC, karan0299 requested changes
Perform the required changes , rest  LGTM

2020-03-16 17:35 UTC, shreyaa-s commented
@karan0299 done!

2020-03-16 17:38 UTC, karan0299 commented
Have you done testing?

2020-03-16 17:58 UTC, merged